title: Marisa Sloan
logo: images/1636161395752.jpg
description: Experienced professional with 5+ years in website management and product development, specializing in healthcare, finance, and technology markets. I'm passionate about building products that improve quality of life for the people using them.
#show_downloads: true
theme: jekyll-theme-minimal
