title: Marisa Sloan
logo: images/1636161395752.jpg
description: Experienced professional in website management and product development, specializing in healthcare, finance, and technology markets. 
#show_downloads: true
theme: jekyll-theme-minimal
